version: '3.7'

services:
  # app:
  #   container_name: api
  #   build: .
  #   depends_on:
  #    - redis
  #   ports:
  #    - 3000:3000
  #   networks:
  #     - redis-network
  #   volumes:
  #    - .:/usr/app
  #    - /usr/app/node_modules
  #   environment:
  #     NODE_ENV: dev
  #     PORT: 3000
  
  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
     - 6379:6379
    networks:
      - redis-network
    environment:
      REDIS_PASSWORD: redispass

networks:
  redis-network: